#service name can be anything, this is the start, have to consistent from now on
#Del already created s3 bucket for us in the deployjment bucket:, so we just refer to his bucket.

service: enchen
frameworkVersion: '3'

provider: 
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  deploymentBucket:
    name: cohort2.serverless.deploys

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  environment:
    ACCESS_KEY: ${ssm:chen-string }

plugins:
  - serverless-offline

